### ISSUE TITLE
plugin does not properly detect ovelay mount on CentOS7

### ISSUE THREAD

**Issue by pyther** [shaded-enmity/yum-overlayfs#1]
In a centos7 container, `overlay / overlay` is the second line entry in `/etc/mtab`.

The `should_touch()` function reads to the first line of `/etc/mtab`. In this case the first line is `rootfs / rootfs rw 0 0`.

I tried this plugin due to [RH#1256299](https://bugzilla.redhat.com/show_bug.cgi?id=1256299). If you would like I can submit a pull request. However, I am not sure if this is the best approach, just a quick hack to test the plugin.

``` diff
--- baseimg/overlayfs/overlayfs.py.orig 2015-08-24 12:24:00.067498108 -0400
+++ baseimg/overlayfs/overlayfs.py  2015-08-24 12:39:10.807999806 -0400
@@ -65,8 +65,9 @@ def should_touch():
         if not path.exists(mtab):
                 return False
         with open(mtab, 'r') as f:
-                line = f.readline()
-                return line.startswith('overlay / overlay')
+                for line in f.readlines():
+           if line.startswith('overlay / overlay'):
+               return True
         return False

 def prereposetup_hook(conduit):
```

created a gist as it seems like the code parser is not handling the tabs correctly. https://gist.github.com/pyther/fb8bc6d5edb6addd124a

**Comment by shaded-enmity** [comment]
Thanks for the report.

I've pushed an updating commit.

This check there is merely a safeguard to not copy up on other file systems, maybe we should get rid of it completely.

**Comment by shaded-enmity** [comment]
In the end, we decided to remove the check. The changes have been merged upstream and I'm obsoleting this repo.

https://github.com/rpm-software-management/yum-utils/tree/master/plugins/ovl
